jobs:
  vitest-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install dependencies
        run: yarn install

      - name: Run coverage on PR
        run: yarn test:coverage

      - name: Save PR coverage
        run: |
          mkdir -p pr-coverage
          cp coverage/coverage-summary.json pr-coverage/

      # Switch to actual main branch
      - name: Checkout main branch
        run: |
          git fetch origin main
          git checkout origin/main

      - name: Install deps (main)
        run: yarn install

      - name: Run coverage on main
        run: yarn test:coverage

      - name: Save base coverage
        run: |
          mkdir -p base-coverage
          cp coverage/coverage-summary.json base-coverage/

      - name: Run vite-pr-coverage-insight action
        uses: subhashmahimaluri/vite-pr-coverage-insight@main
        with:
          github-token: ${{ secrets.GH_BOT_TOKEN }}
          base: base-coverage/coverage-summary.json
          head: pr-coverage/coverage-summary.json
