name: PR Coverage Report

on:
  pull_request_target:
    branches:
      - main

jobs:
  vitest-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run coverage on PR
        run: |
          set -e
          yarn test:coverage || echo "⚠️ Tests failed, continuing to the report generation step"
        continue-on-error: true

      - name: Save PR coverage
        if: always()
        run: |
          mkdir -p pr-coverage
          if [ -f coverage/coverage-summary.json ]; then
            cp coverage/coverage-summary.json pr-coverage/
          else
            echo '{}' > pr-coverage/coverage-summary.json
            echo "⚠️ Created empty coverage file as tests failed"
          fi

      - name: Checkout main branch
        run: |
          git fetch origin main
          git checkout origin/main

      - name: Install dependencies (main)
        run: yarn install --frozen-lockfile

      - name: Run coverage on main
        run: yarn test:coverage

      - name: Save base coverage
        run: |
          mkdir -p base-coverage
          cp coverage/coverage-summary.json base-coverage/

      - name: Run vite-pr-coverage-insight action
        uses: subhashmahimaluri/vite-pr-coverage-insight@v1.3.2
        if: always()
        with:
          github-token: ${{ secrets.GH_BOT_TOKEN }}
          base: base-coverage/coverage-summary.json
          head: pr-coverage/coverage-summary.json
          test-failures: test-failures.json
          use-check-run: true
          cache-buster: ${{ github.run_id }}
