name: PR Coverage Report

on:
  pull_request_target:
    branches:
      - main

jobs:
  vitest-coverage:
    runs-on: ubuntu-latest

    steps:
      # ✅ Checkout PR code explicitly (not default main)
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      # ✅ Setup Node environment
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # ✅ Install dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # ✅ Run coverage on PR
      - name: Run coverage on PR
        run: yarn test:coverage

      - name: Save PR coverage
        run: |
          mkdir -p pr-coverage
          cp coverage/coverage-summary.json pr-coverage/

      # ✅ Checkout main to compare base coverage
      - name: Checkout main branch
        run: |
          git fetch origin main
          git checkout origin/main

      - name: Install dependencies (main)
        run: yarn install --frozen-lockfile

      - name: Run coverage on main
        run: yarn test:coverage

      - name: Save base coverage
        run: |
          mkdir -p base-coverage
          cp coverage/coverage-summary.json base-coverage/

      # ✅ Run PR Coverage Insight Action with GH token
      - name: Run vite-pr-coverage-insight action
        uses: subhashmahimaluri/vite-pr-coverage-insight@v1.2.4
        with:
          github-token: ${{ secrets.GH_BOT_TOKEN }}
          base: base-coverage/coverage-summary.json
          head: pr-coverage/coverage-summary.json
          cache-buster: ${{ github.run_id }}
